name: tri
version: 0.0.1
description: trinary stuff
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  libpen: any
  logging_handlers: any
  unittest: any
  async_await:
    git: https://github.com/dart-lang/async_await.git
transformers:
- async_await